name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make tar

      - name: Download and extract CEdev
        run: |
          curl -sL https://github.com/CE-Programming/toolchain/releases/latest/download/CEdev-Linux.tar.gz | tar xz
      
      - name: Add CEdev to PATH
        run: |
          echo "CEdev/bin" >> $GITHUB_PATH
          echo $GITHUB_PATH
      
      - name: Make GFX
        run: make gfx

      - name: Build TINET.8xp
        run: make

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: dev-$(date +%Y%m%d)
          release_name: Development Release - $(date +%Y/%m/%d)
          body: |
            Built from commit(s):
            $(git log --oneline -n 10)
          draft: true

      - name: Upload TINET.8xp
        uses: actions/upload-artifact@v2
        with:
          name: TINET.8xp
          path: bin/TINET.8xp

      - name: Set commit status
        uses: actions/github-script@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const ghContext = github.context;
            const { owner, repo } = ghContext.repo;
            const sha = ghContext.sha;
            const state = 'success';
            const description = 'Build succeeded';
            const contextName = 'build';
            github.repos.createStatus({ owner, repo, sha, state, description, context: contextName });