name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get repository information
        uses: actions/github-script@v5
        with:
          script: |
            const repo = context.payload.repository.full_name;
            console.log(`The repository is ${repo}`);

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make tar

      - name: Download and extract CEdev
        run: |
          curl -sL https://github.com/CE-Programming/toolchain/releases/latest/download/CEdev-Linux.tar.gz | tar xz
      
      - name: Add CEdev to PATH
        run: |
          echo "CEdev/bin" >> $GITHUB_PATH
          echo $GITHUB_PATH
      
      - name: Make GFX
        run: make gfx

      - name: Build TINET.8xp
        run: make

      - name: "Create release"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          script: |
            try {
              const response = await github.rest.repos.createRelease({
                draft: false,
                generate_release_notes: true,
                name: process.env.RELEASE_TAG,
                owner: context.repo.owner,
                prerelease: true,
                repo: context.repo.repo,
                tag_name: process.env.RELEASE_TAG,
              });

              core.exportVariable('RELEASE_ID', response.data.id);
              core.exportVariable('RELEASE_UPLOAD_URL', response.data.upload_url);
            } catch (error) {
              core.setFailed(error.message);
            }

      - name: Upload TINET.8xp
        uses: actions/upload-artifact@v2
        with:
          name: TINET.8xp
          path: bin/TINET.8xp

      - name: Set commit status
        uses: |
          actions/github-script@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const ghContext = github.context;
            const { owner, repo } = github.context.repo;
            const sha = ghContext.sha;
            const state = 'success';
            const description = 'Build succeeded';
            const contextName = 'build';
            github.repos.createStatus({ owner, repo, sha, state, description, context: contextName });