name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y make tar

      - name: Download and extract CEdev
        run: |
          curl -sL https://github.com/CE-Programming/toolchain/releases/latest/download/CEdev-Linux.tar.gz | tar xz -C $HOME
          echo "export PATH=$HOME/CEdev/bin:\$PATH" >> $GITHUB_ENV

      - name: Build TINET.8xp
        run: make

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: dev-$(date +%Y%m%d)
          release_name: Development Release - $(date +%Y/%m/%d)
          body: |
            Built from commit(s):
            $(git log --oneline -n 10)
          draft: true

      - name: Upload TINET.8xp
        uses: actions/upload-artifact@v2
        with:
          name: TINET.8xp
          path: bin/TINET.8xp

      - name: Set commit status
        uses: einaregilsson/commit-status-action@v1
        with:
          status: success
          token: ${{ secrets.GITHUB_TOKEN }}
          description: Build succeeded
